apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    # keep: prevent helm uninstall from deleting the namespace and its external secrets
    helm.sh/resource-policy: keep
  labels:
    {{- include "cima-x.labels" . | nindent 4 }}
