apiVersion: v1
kind: ConfigMap
metadata:
  name: orthanc-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cima-x.labels" . | nindent 4 }}
data:
  orthanc.json: |
    {
      "StorageDirectory": "/data",
      "DicomAet": {{ .Values.orthanc.aet | quote }},
      "DicomPort": {{ .Values.orthanc.dicomPort }},
      "HttpPort": {{ .Values.orthanc.httpPort }},
      "RemoteAccessAllowed": true,
      "AuthenticationEnabled": true,
      "Plugins": {{ .Values.orthanc.plugins | toJson }},
      "IngestTranscoding": {{ .Values.orthanc.ingestTranscoding | quote }}
    }
