apiVersion: v1
kind: Service
metadata:
  name: orthanc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cima-x.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: orthanc
  ports:
  - name: dicom
    port: {{ .Values.orthanc.dicomPort }}
    targetPort: {{ .Values.orthanc.dicomPort }}
    nodePort: {{ .Values.orthanc.nodePorts.dicom }}
    protocol: TCP
  - name: http
    port: {{ .Values.orthanc.httpPort }}
    targetPort: {{ .Values.orthanc.httpPort }}
    nodePort: {{ .Values.orthanc.nodePorts.http }}
    protocol: TCP
